
function svg_left(svgElement,callbackUrl) {
    svg_translate(svgElement, -20, 0);
    svg_wicket_call(callbackUrl, "transform", "translate(-20,0)")
}

function svg_right(svgElement,callbackUrl) {
    svg_translate(svgElement, 20, 0)
    svg_wicket_call(callbackUrl, "transform", "translate(20,0)")
}

function svg_up(svgElement,callbackUrl) {
    svg_translate(svgElement, 0, -20)
    svg_wicket_call(callbackUrl, "transform", "translate(0,-20)")
}

function svg_down(svgElement,callbackUrl) {
    svg_translate(svgElement, 0, 20)
    svg_wicket_call(callbackUrl, "transform", "translate(0,20)")
}

function svg_zoomIn(svgElement,callbackUrl) {
    svg_setScale(svgElement, 1.25, 1.25);
    svg_wicket_call(callbackUrl, "transform", "scale(1.25, 1.25)")
}

function svg_zoomOut(svgElement,callbackUrl) {
    svg_setScale(svgElement, 0.75, 0.75);
    svg_wicket_call(callbackUrl, "transform", "scale(0.75, 0.75)")
}

function svg_reset(svgElement,callbackUrl) { // restore first 3 transforms (generated by GraphViz)
    var transformList = getTransformList(svgElement);
    var xform0 = transformList.getItem(0);
    var xform1 = transformList.getItem(1);
    var xform2 = transformList.getItem(2);
    transformList.clear();
    transformList.appendItem(xform0);
    transformList.appendItem(xform1);
    transformList.appendItem(xform2);
    svg_wicket_call(callbackUrl, "transform", "clear")
}

function svg_translate(svgElement, x, y) {
    var xform = getSVGTransform(svgElement);
    xform.setTranslate(x, y);
    getTransformList(svgElement).appendItem(xform);
}

function svg_setScale(svgElement, x, y) {
    var xform = getSVGTransform(svgElement);
    xform.setScale(x, y);
    getTransformList(svgElement).appendItem(xform);
}

function getTransformList(svgElement) {
    var graphNode = getGraphNode(svgElement)
    return graphNode.transform.baseVal;
}

function getGraphNode(svgElement) {
    return getSVGElement(svgElement).childNodes[1]
}

function getSVGTransform(svgElement) {
    return getSVGElement(svgElement).createSVGTransform();
}

function getSVGElement(svgElement) {
    return document.getElementById(svgElement);
}

function svg_wicket_call(callbackUrl, arg, val) {
    alert("Calling back to " + callbackUrl + " with " + arg + "=" + val)
    wicketAjaxGet(callbackUrl + '&' + arg + '=' + val, function() { }, function() { });
}
