package com.mindalliance.channels.playbook.rules

import com.mindalliance.channels.playbook.analysis.*
import com.mindalliance.channels.playbook.ifm.*
import com.mindalliance.channels.playbook.ref.*
import org.apache.log4j.Logger
import org.drools.spi.KnowledgeHelper

function void inferFrom(KnowledgeHelper drools, Referenceable cause, AnalysisElement analysis, String rationale) {
    analysis.setRationale(rationale);
    drools.insertLogical(analysis);
    log(cause, analysis);
}

function void log(Referenceable cause, AnalysisElement analysis) {
    Logger.getLogger("rules").info("Inferred " + analysis + " from " + cause + "(" + cause.getReference() + ")" );
}

