package com.mindalliance.channels.playbook.rules

import com.mindalliance.channels.playbook.ref.*
import com.mindalliance.channels.playbook.ifm.*
import com.mindalliance.channels.playbook.ifm.definition.*
import com.mindalliance.channels.playbook.ifm.info.*
import com.mindalliance.channels.playbook.ifm.project.environment.*
import com.mindalliance.channels.playbook.ifm.playbook.*
import com.mindalliance.channels.playbook.analysis.*
import com.mindalliance.channels.playbook.analysis.profile.*
import java.util.*

#### Validate information acts ####

rule "invalid information act"
    agenda-group "validations"
    when
        $el:  InformationAct($actor:actorAgent)
        eval(!Channels.isSet($actor))
    then
        inferFrom(drools, $el, new Invalid($el), "The actor is missing");
    end

rule "invalid flow act target"
    agenda-group "validations"
    when
        $el: FlowAct($target:targetAgent)
        eval(!Channels.isSet($target))
    then
        inferFrom(drools, $el, new Invalid($el), "The target agent is missing");
    end

rule "invalid flow act information"
    agenda-group "validations"
    when
        $el: SharingAct($info:information)
        eval(!$info.isDefined())
    then
        inferFrom(drools, $el, new Invalid($el), "The shared information is not defined");
    end

rule "invalid flow act - sender is receiver"
    agenda-group "validations"
    when
        $el: FlowAct($actor:actorAgent, targetAgent == $actor)
    then
        inferFrom(drools, $el, new Invalid($el), "The sender can not also be the receiver");
    end

rule "invalid assignation assignee"
    agenda-group "validations"
    when
        $el: Assignation($assignee:assigneeAgent)
        eval(!Channels.isSet($assignee))
    then
        inferFrom(drools, $el, new Invalid($el), "The assignee is missing");
    end

rule "invalid assignation responsibility"
    agenda-group "validations"
    when
        $el: Assignation($responsibility:responsibility)
        eval(!$responsibility.isDefined())
    then
        inferFrom(drools, $el, new Invalid($el), "The responsibility is undefined");
    end

rule "invalid association associate"
    agenda-group "validations"
    when
        $el: Association($associate:toAgent)
        eval(!Channels.isSet($associate))
    then
        inferFrom(drools, $el, new Invalid($el), "The associate is missing");
    end

rule "invalid association relationship"
    agenda-group "validations"
    when
        $el: Association($name:relationshipName)
        eval($name.trim().isEmpty())
    then
        inferFrom(drools, $el, new Invalid($el), "No relationship name");
    end

rule "invalid information request need"
    agenda-group "validations"
    when
        $el: InformationRequest($need:informationNeed)
        eval(!$need.isDefined())
    then
        inferFrom(drools, $el, new Invalid($el), "The information need is unspecified");
    end

rule "invalid relocation"
    agenda-group "validations"
    when
        $el: InformationRequest($location:location)
        eval(!$location.isDefined())
    then
        inferFrom(drools, $el, new Invalid($el), "The location not defined");
    end

rule "invalid sharing commitment"
    agenda-group "validations"
    when
        $el: SharingCommitment($protocol:protocol)
        eval(!$protocol.isDefined())
    then
        inferFrom(drools, $el, new Invalid($el), "The sharing protocol is not defined");
    end

rule "invalid sharing request protocol"
    agenda-group "validations"
    when
        $el: SharingRequest($protocol:protocol)
        eval(!$protocol.isDefined())
    then
        inferFrom(drools, $el, new Invalid($el), "The sharing protocol is not defined");
    end

rule "invalid sharing request information spec"
    agenda-group "validations"
    when
        $el: SharingRequest($infoSpec:protocol.informationSpec)
        eval(!((InformationDefinition)$infoSpec).matchesAll())
    then
        inferFrom(drools, $el, new Invalid($el), "The sharing protocol is not defined");
    end

### Validate project elements

rule "invalid sharing agreement"
    agenda-group "validations"      // TODO break into smaller rules for pointed diagnostic
    when
        $el: SharingAgreement($source:source, $recipient:recipient, $protocol:protocol, $constraints:constraints)
        eval(!Channels.isSet($source) || !Channels.isSet($recipient) || !$protocol.isDefined())
    then
        inferFrom(drools, $el, new Invalid($el), "The sharing agreement is not sufficiently defined");
    end

rule "invalid policy"
    agenda-group "validations"         // TODO break into smaller rules for pointed diagnostic
    when
        $el: Policy($sourceSpec:sourceSpec, $recipientSpec:recipientSpec, $infoSpec:informationSpec, $rels: relationshipNames)
        eval($sourceSpec.matchesAll() || $infoSpec.matchesAll() || ($recipientSpec.matchesAll() && $rels.isEmpty()) )
    then
        inferFrom(drools, $el, new Invalid($el), "The policy is not sufficiently defined.");
    end

rule "invalid relationship"
    agenda-group "validations"        // TODO break into smaller rules for pointed diagnostic
    when
        $el: Relationship($from: fromAgent, $to: toAgent, $name: name)
        eval(!Channels.isSet($from) || !Channels.isSet($to) || $name.isEmpty())
    then
        inferFrom(drools, $el, new Invalid($el), "The relationship is not sufficiently defined.");
    end


### Validate model elements

### Validate other playbook elements
