// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mindalliance.sb.model;

import com.mindalliance.sb.model.IncidentSystemPK;
import java.io.Serializable;

privileged aspect IncidentSystemPK_Roo_Serializable {
    
    declare parents: IncidentSystemPK implements Serializable;
    
    private static final long IncidentSystemPK.serialVersionUID = 1L;
    
}
