// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mindalliance.sb.model;

import com.mindalliance.sb.model.IncidentSystemPK;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect IncidentSystemPK_Roo_Configurable {
    
    declare @type: IncidentSystemPK: @Configurable;
    
}
