// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mindalliance.sb.model;

import com.mindalliance.sb.model.OrganizationCapability;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect OrganizationCapability_Roo_Configurable {
    
    declare @type: OrganizationCapability: @Configurable;
    
}
