// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mindalliance.sb.model;

import com.mindalliance.sb.model.SharingMediumPK;
import java.io.Serializable;

privileged aspect SharingMediumPK_Roo_Serializable {
    
    declare parents: SharingMediumPK implements Serializable;
    
    private static final long SharingMediumPK.serialVersionUID = 1L;
    
}
