// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mindalliance.sb.model;

import com.mindalliance.sb.model.SharedInfoPK;
import java.io.Serializable;

privileged aspect SharedInfoPK_Roo_Serializable {
    
    declare parents: SharedInfoPK implements Serializable;
    
    private static final long SharedInfoPK.serialVersionUID = 1L;
    
}
