// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mindalliance.sb.model;

import com.mindalliance.sb.model.SuperbowlPlannerPK;
import java.io.Serializable;

privileged aspect SuperbowlPlannerPK_Roo_Serializable {
    
    declare parents: SuperbowlPlannerPK implements Serializable;
    
    private static final long SuperbowlPlannerPK.serialVersionUID = 1L;
    
}
